### Tensor operations

In [1]:
# pytorch is preinstalled on google collab
# else: pip install torch

import torch
print(torch.__version__)

# checking if GPU available
# get_device_name  : shows which GPU is available
# as of now shows CPU : If needed GPU : change runtime type : GPU

if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

2.5.1+cu121
GPU is available!
Using GPU: Tesla T4


In [2]:
torch.cuda.is_available()

True

In [3]:
# we will now store our GPU device and assign it to a variable

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

device(type='cuda')

In [4]:
# creating a new tensor on GPU

torch.rand(size=(2,3), device=device)

tensor([[0.6934, 0.0343, 0.4571],
        [0.6496, 0.5724, 0.6945]], device='cuda:0')

In [6]:
# moving an existing tensor on CPU onto GPU

# create a tensor on CPU

a = torch.rand(size=(2,3))

a
# this tensor lies on CPU

tensor([[0.0873, 0.2355, 0.2195],
        [0.9818, 0.4430, 0.3167]])

In [9]:
b = a.to(device)
b
# this tensor lies on GPU

tensor([[0.0873, 0.2355, 0.2195],
        [0.9818, 0.4430, 0.3167]], device='cuda:0')

In [10]:
# now whatever operations you do , they will be done on GPU
b + 5

tensor([[5.0873, 5.2355, 5.2195],
        [5.9818, 5.4430, 5.3167]], device='cuda:0')

In [4]:
# create a 10000 x 10000 matrix

import time
import torch

# define the size
size = 10000

# create two matrices on cpu
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# measure the time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time


print(f"Time on CPU : {cpu_time:.4f} seconds ")

# move matrices on GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# measure the time on GPU

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU : {gpu_time:.4f} seconds ")

#compare results and the gain

print("Gain",cpu_time/gpu_time)
# this means the job that takes 30 hours on a CPU can be finished on a GPU in an hour


Time on CPU : 17.4845 seconds 
Time on GPU : 0.5739 seconds 
Gain 30.46778297887014
